name: whereismyintern
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.9.0
  flutter_easyloading: ^3.0.5
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  lottie: ^2.2.0
  flutter_screenutil: ^5.7.0
  curved_navigation_bar: ^1.0.3
  flutter_animate: ^4.1.1+1
  file_picker: ^5.3.4
  firebase_core_platform_interface: ^4.5.1
  cached_network_image: ^3.2.3
  numberpicker: ^2.1.1
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  sliding_up_panel: ^2.0.0+1






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  image: "assets/png/splash_logo.png"
  android: true
  ios: true
  color: "#0D0C0C"

  android_12:
    image: "assets/png/splash_logo.png"
    color: "#0D0C0C"
    icon_background_color: "#0D0C0C"
 
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/splash_logo.png"
  adaptive_icon_background: "#0D0C0C"

 
flutter:

  uses-material-design: true
  assets:
    - assets/json/
    - assets/png/
  